# Generated by Django 2.2.2 on 2020-01-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50)),
                ('post_details', models.TextField()),
                ('post_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
